import { registerBashTool } from "./bash-tool.ts";
import { registerEditTool } from "./edit-tool.ts";
import { registerReadTool } from "./read-tool.ts";
import { registerSearchTools } from "./search-tools.ts";
import { registerWriteTool } from "./write-tool.ts";

/** Composition-only wiring for the seven built-in tool presenters. */
export function registerBuiltinTools(env: any): void {
	const {
		cwd, registerBuiltinOverride, forwardedToolContract, hostToolSettings, hostSettingsContext,
		spl, sp, syncToolCallStatus, stableCallSummary, makeText, toolHeader, toolStatusDot,
		withBranch, withFinalBranchBlock, renderToolTextLines, setupBlinkTimer, clearBlinkTimer, setToolStatus,
		firstImageBlock, renderReadImage, shortPath, errorText, resultSentence, claudeChromeEnabled,
		D_BOLD_ON, D_BOLD_OFF, plural, widthAwareText, visualPreviewText, collapsedPreviewCount,
		previewLimit, expandedPreviewLimit, getSettingsRevision, hashText, bashSemanticDisplayEnabled,
		bashOutputMode, bashRunningPreview, bashCollapsedLimit, FG_RULE, D_RST, summarizeDiff,
		shouldRevealCallArgs, hasOwnArg, ccEmphasis, writtenLineCount, renderWidthAwareDiff,
		diffCard, getCachedParsedDiff, diffContentWidth, claudeDiffPaletteEnabled, renderFileListing,
		renderUnified, resolveDiffColors, diffCollapsedLimit, MAX_RENDER_LINES, renderPrewrappedDiffLines,
		indentBranchBlock, computeAggregateEditDiff, computeLocalizedEditDiffs,
		buildAggregateEditPreviewText, buildEditPreviewText,
	} = env;
	registerReadTool({
		cwd,
		register: registerBuiltinOverride,
		forwardContract: forwardedToolContract,
		autoResizeImages: (runtimeCwd, ctx) => hostToolSettings(runtimeCwd, hostSettingsContext(ctx)).autoResizeImages,
		linkedPath: spl,
		syncCallStatus: syncToolCallStatus,
		stableSummary: stableCallSummary,
		makeText,
		header: toolHeader,
		statusDot: toolStatusDot,
		withBranch,
		startBlink: setupBlinkTimer,
		stopBlink: clearBlinkTimer,
		setStatus: setToolStatus,
		firstImage: firstImageBlock,
		renderImage: (result, expanded, theme, ctx) => renderReadImage({ makeText, withBranch, shortPath }, result, expanded, theme, ctx),
		errorText,
		formatReadCount: (theme, count) => resultSentence(
			theme,
			claudeChromeEnabled()
				? `Read ${D_BOLD_ON}${count}${D_BOLD_OFF} ${count === 1 ? "line" : "lines"}`
				: `${plural(count, "line")} loaded`,
		),
		widthAware: widthAwareText,
		visualPreview: (text, width, rows, mode, theme, expanded) => visualPreviewText(text, width, rows, "head", theme, mode, {
			expandHint: !expanded,
			expandedCap: expanded,
		}),
		renderLines: renderToolTextLines,
		collapsedRows: (expanded) => collapsedPreviewCount(expanded, previewLimit()),
		expandedRows: expandedPreviewLimit,
		revision: getSettingsRevision,
		hash: hashText,
	});

	registerBashTool({
		cwd,
		register: registerBuiltinOverride,
		forwardContract: forwardedToolContract,
		hostSettings: (runtimeCwd, ctx) => hostToolSettings(runtimeCwd, hostSettingsContext(ctx)),
		semanticEnabled: bashSemanticDisplayEnabled,
		shortPath: sp,
		syncCallStatus: syncToolCallStatus,
		stableSummary: stableCallSummary,
		makeText,
		header: toolHeader,
		statusDot: toolStatusDot,
		withBranch,
		startBlink: setupBlinkTimer,
		stopBlink: clearBlinkTimer,
		setStatus: setToolStatus,
		errorText,
		widthAware: widthAwareText,
		visualPreview: (text, width, rows, mode, theme, style, options) => visualPreviewText(text, width, rows, mode, theme, style, options),
		renderLines: renderToolTextLines,
		outputMode: bashOutputMode,
		runningPreview: bashRunningPreview,
		collapsedLimit: bashCollapsedLimit,
		collapsedRows: (expanded) => collapsedPreviewCount(expanded, bashCollapsedLimit()),
		expandedRows: expandedPreviewLimit,
		revision: getSettingsRevision,
		hash: hashText,
	});

	registerSearchTools({
		cwd,
		register: registerBuiltinOverride,
		forwardContract: forwardedToolContract,
		shortPath: sp,
		syncCallStatus: syncToolCallStatus,
		stableSummary: stableCallSummary,
		makeText,
		header: toolHeader,
		statusDot: toolStatusDot,
		withBranch,
		startBlink: setupBlinkTimer,
		stopBlink: clearBlinkTimer,
		setStatus: setToolStatus,
		widthAware: widthAwareText,
		renderLines: renderToolTextLines,
		visualPreview: (text, width, rows, theme) => visualPreviewText(text, width, rows, "head", theme, "dim", { expandedCap: true }),
		expandedLimit: expandedPreviewLimit,
		revision: getSettingsRevision,
		hash: hashText,
		fgRule: () => FG_RULE,
		reset: () => D_RST,
	});

	registerWriteTool({
		cwd,
		register: registerBuiltinOverride,
		forwardContract: forwardedToolContract,
		summarizeDiff,
		linkedPath: spl,
		revealArgs: shouldRevealCallArgs,
		hasArg: hasOwnArg,
		syncCallStatus: syncToolCallStatus,
		stableSummary: stableCallSummary,
		makeText,
		header: toolHeader,
		statusDot: toolStatusDot,
		withBranch,
		withFinalBranch: withFinalBranchBlock,
		startBlink: setupBlinkTimer,
		stopBlink: clearBlinkTimer,
		setStatus: setToolStatus,
		resultSentence,
		emphasis: ccEmphasis,
		writtenLineCount,
		renderWidthAwareDiff,
		diffCard: (last, key, placeholder, build, invalidate, textRenderer, fallback) => diffCard(last, key, placeholder, build, invalidate, textRenderer, fallback),
		cachedDiff: getCachedParsedDiff,
		diffContentWidth,
		claudeDiffPalette: claudeDiffPaletteEnabled,
		renderFileListing,
		renderUnified,
		resolveDiffColors,
		collapsedLimit: diffCollapsedLimit,
		maxRenderLines: MAX_RENDER_LINES,
		renderPrewrapped: renderPrewrappedDiffLines,
		hash: hashText,
		revision: getSettingsRevision,
	});

	registerEditTool({
		cwd,
		register: registerBuiltinOverride,
		forwardContract: forwardedToolContract,
		summarizeDiff,
		linkedPath: spl,
		revealArgs: shouldRevealCallArgs,
		hasArg: hasOwnArg,
		stableSummary: stableCallSummary,
		syncCallStatus: syncToolCallStatus,
		makeText,
		header: toolHeader,
		statusDot: toolStatusDot,
		withBranch,
		indentBranch: indentBranchBlock,
		startBlink: setupBlinkTimer,
		stopBlink: clearBlinkTimer,
		setStatus: setToolStatus,
		resultSentence,
		diffCard: (last, key, placeholder, build, invalidate, textRenderer, fallback) => diffCard(last, key, placeholder, build, invalidate, textRenderer, fallback),
		computeAggregate: computeAggregateEditDiff,
		computeLocalized: computeLocalizedEditDiffs,
		buildAggregate: buildAggregateEditPreviewText,
		buildPreview: buildEditPreviewText,
		renderPrewrapped: renderPrewrappedDiffLines,
		hash: hashText,
		revision: getSettingsRevision,
	});

}
